<a href="https://colab.research.google.com/github/KyryloChalov/DS/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
print('1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.')
print('-'*50)

a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a)

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
--------------------------------------------------
[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
import numpy as np
print('2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.')
print('-'*50)

print('варіант 1:')
a = np.array([[0,0,0],[0,0,0],[0,0,0]])
print(a)

print('варіант 2:')
b = np.zeros((3,3), dtype=int)
print(b)

2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
--------------------------------------------------
варіант 1:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
варіант 2:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [5]:
import numpy as np
print('3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.')
print('-'*50)

a = np.random.randint(1, 11, size=(5,5))
print(a)

3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
--------------------------------------------------
[[8 1 8 8 8]
 [5 6 6 3 8]
 [2 4 4 2 7]
 [4 6 4 5 3]
 [8 2 4 2 9]]


In [6]:
import numpy as np
print('4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.')
print('-'*50)

a = np.random.rand(4,4)
print(a)

4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
--------------------------------------------------
[[0.15198152 0.19057583 0.81362595 0.16453087]
 [0.50337928 0.76980567 0.41386699 0.0117748 ]
 [0.70737488 0.42926318 0.96175408 0.13700495]
 [0.61048277 0.28203354 0.34708568 0.81017427]]


In [7]:
import numpy as np
print('5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.')
print('-'*50)

a = np.random.randint(1, 11, size=(5))
print('    a =', a)

b = np.random.randint(1, 11, size=(5))
print('    b =', b)

c = a + b
print('a + b =', c)

d = a - b
print('a - b =', d)

e = a * b
print('a * b =', e)


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
--------------------------------------------------
    a = [5 6 6 6 8]
    b = [ 4 10  3  9  3]
a + b = [ 9 16  9 15 11]
a - b = [ 1 -4  3 -3  5]
a * b = [20 60 18 54 24]


In [8]:
import numpy as np
print('6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.')
print('-'*50)

a = np.random.rand(7)
print('a =\n', a)

b = np.random.rand(7)
print('b =\n', b)

c = np.dot(a, b)
print('Скалярний добуток:\n', c)

6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
--------------------------------------------------
a =
 [0.18854778 0.47432651 0.83742154 0.00884345 0.69423842 0.83581186
 0.91482648]
b =
 [0.62623484 0.73971194 0.72544858 0.43393866 0.47732789 0.11924759
 0.43843613]
Скалярний добуток:
 1.9124248341472558


In [9]:
import numpy as np
print('7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.')
print('-'*50)

a = np.random.randint(1, 11, size=(2,2))
print('a =\n', a)

b = np.random.randint(1, 11, size=(2,3))
print('b =\n', b)

c = np.dot(a, b)
print('Множення матриць:\n', c)

7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
--------------------------------------------------
a =
 [[ 7  8]
 [ 9 10]]
b =
 [[ 2  3  3]
 [ 1  3 10]]
Множення матриць:
 [[ 22  45 101]
 [ 28  57 127]]


In [10]:
import numpy as np
print('8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.')
print('-'*50)

a = np.random.randint(1, 11, size=(3,3))
print('a =\n', a)

c = np.linalg.inv(a)
print('Обернена матриця:\n', c)

8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
--------------------------------------------------
a =
 [[ 6  2  7]
 [ 1 10  2]
 [ 1  7  8]]
Обернена матриця:
 [[ 0.18181818  0.09090909 -0.18181818]
 [-0.01652893  0.11294766 -0.0137741 ]
 [-0.00826446 -0.11019284  0.15977961]]


In [11]:
import numpy as np
print('9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.')
print('-'*50)

a = np.random.rand(4,4)
print('a =\n', a)

c = a.T
print('Транспонована матриця:\n', c)

9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
--------------------------------------------------
a =
 [[0.70004321 0.18053654 0.5131474  0.97656165]
 [0.37126348 0.91962875 0.91568994 0.57040721]
 [0.48040081 0.77417392 0.88509122 0.57039123]
 [0.02450334 0.16953957 0.99093606 0.34304249]]
Транспонована матриця:
 [[0.70004321 0.37126348 0.48040081 0.02450334]
 [0.18053654 0.91962875 0.77417392 0.16953957]
 [0.5131474  0.91568994 0.88509122 0.99093606]
 [0.97656165 0.57040721 0.57039123 0.34304249]]


In [12]:
import numpy as np
print('10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.')
print('-'*50)

a = np.random.randint(1, 11, size=(3,4))
print('a =\n', a)

b = np.random.randint(1, 11, size=(4))
print('b =\n', b)

c = np.dot(a, b)
print('Множення матриці на вектор:\n', c)

10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
--------------------------------------------------
a =
 [[ 5  1  7  8]
 [ 4  9 10  6]
 [10  7  1  8]]
b =
 [ 2  1  1 10]
Множення матриці на вектор:
 [ 98  87 108]


In [13]:
import numpy as np
print('11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.')
print('-'*50)

a = np.random.rand(2,3)
print('a =\n', a)

b = np.random.rand(3)
print('b =\n', b)

c = np.dot(a, b)
print('Множення матриці на вектор:\n', c)

11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
--------------------------------------------------
a =
 [[0.04928294 0.7056704  0.20946406]
 [0.40447755 0.46264124 0.96020991]]
b =
 [0.95676008 0.88286792 0.17653218]
Множення матриці на вектор:
 [0.70714286 0.96494703]


In [14]:
import numpy as np
print('12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.')
print('-'*50)

a = np.random.randint(1, 11, size=(2,2))
print('a =\n', a)

b = np.random.randint(1, 11, size=(2,2))
print('b =\n', b)

c = a * b
print('Поелементне множення:\n', c)

12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
--------------------------------------------------
a =
 [[ 8  1]
 [ 7 10]]
b =
 [[9 3]
 [1 7]]
Поелементне множення:
 [[72  3]
 [ 7 70]]


In [15]:
import numpy as np
print('13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.')
print('-'*50)

a = np.random.randint(1, 11, size=(2,2))
print('a =\n', a)

b = np.random.randint(1, 11, size=(2,2))
print('b =\n', b)

c = a + b
print('Добуток:\n', c)

13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
--------------------------------------------------
a =
 [[1 6]
 [1 6]]
b =
 [[8 5]
 [6 6]]
Добуток:
 [[ 9 11]
 [ 7 12]]


In [16]:
import numpy as np
print('14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.')
print('-'*50)

a = np.random.randint(1, 101, size=(5,5))
print('a =\n', a)

c = a.sum()
print('Сума всіх елементів:\n', c)

14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
--------------------------------------------------
a =
 [[27 97 98 43 92]
 [98 48 37 77 52]
 [50 25  5 47 52]
 [78 68 54  1 63]
 [68 63 99 45 58]]
Сума всіх елементів:
 1445


In [17]:
import numpy as np
print('15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.')
print('-'*50)

a = np.random.randint(1, 11, size=(4,4))
print('a =\n', a)

b = np.random.randint(1, 11, size=(4,4))
print('b =\n', b)

c = a - b
print('a - b =\n', c)

15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
--------------------------------------------------
a =
 [[6 3 2 3]
 [4 1 5 7]
 [5 6 7 9]
 [3 4 3 8]]
b =
 [[1 4 6 7]
 [5 5 3 7]
 [8 6 3 5]
 [1 1 7 2]]
a - b =
 [[ 5 -1 -4 -4]
 [-1 -4  2  0]
 [-3  0  4  4]
 [ 2  3 -4  6]]


In [18]:
import numpy as np
print('16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.')
print('-'*50)

a = np.random.rand(3,3)
print('a =\n', a)

b = np.zeros(3, dtype=float)

for i in range(a.shape[0]):
  b[i] = a[i].sum()

c = b.reshape(-1, 1)
print('Суми елементів кожного рядка матриці:\n',c)


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
--------------------------------------------------
a =
 [[0.94547794 0.28960618 0.58732576]
 [0.0016428  0.21720257 0.60627664]
 [0.87363315 0.48028732 0.59822749]]
Суми елементів кожного рядка матриці:
 [[1.82240988]
 [0.82512201]
 [1.95214796]]


In [19]:
import numpy as np
print('17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.')
print('-'*50)

a = np.random.randint(1, 11, size=(3,4))
print('a =\n', a)

b = np.power(a, 2)
print('a ** 2 =\n', b)

17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
--------------------------------------------------
a =
 [[ 5  9  9  6]
 [10  4  8  1]
 [ 1  5  2  1]]
a ** 2 =
 [[ 25  81  81  36]
 [100  16  64   1]
 [  1  25   4   1]]


In [20]:
import numpy as np
print('18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.')
print('-'*50)

a = np.random.randint(1, 51, size=(4))
print('a =\n', a)

b = np.sqrt(a)
print('sqrt(a) =\n', b)

18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.
--------------------------------------------------
a =
 [ 9 31 18  2]
sqrt(a) =
 [3.         5.56776436 4.24264069 1.41421356]
