<a href="https://colab.research.google.com/github/KyryloChalov/DS/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [145]:
import numpy as np
print('1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.')
print('-'*50)

a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a)

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
--------------------------------------------------
[ 1  2  3  4  5  6  7  8  9 10]


In [146]:
import numpy as np
print('2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.')
print('-'*50)

print('варіант 1:')
a = np.array([[0,0,0],[0,0,0],[0,0,0]])
print(a)

print('варіант 2:')
b = np.zeros((3,3), dtype=int)
print(b)

2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
--------------------------------------------------
варіант 1:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
варіант 2:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [147]:
import numpy as np
print('3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.')
print('-'*50)

a = np.random.randint(1, 11, size=(5,5))
print(a)

3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
--------------------------------------------------
[[ 3  5  1  7  9]
 [ 2  1  2  7  9]
 [ 1  6  6  8  3]
 [ 2  9  9  2  1]
 [ 4 10  2  4  1]]


In [148]:
import numpy as np
print('4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.')
print('-'*50)

a = np.random.rand(4,4)
print(a)

4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
--------------------------------------------------
[[0.56150344 0.17735959 0.96090679 0.79943404]
 [0.25499095 0.74632626 0.03693469 0.57784478]
 [0.69454013 0.16513512 0.67471311 0.33160505]
 [0.62224325 0.01208037 0.97749318 0.7533073 ]]


In [149]:
import numpy as np
print('5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.')
print('-'*50)

a = np.random.randint(1, 11, size=(5))
print('    a =', a)

b = np.random.randint(1, 11, size=(5))
print('    b =', b)

c = a + b
print('a + b =', c)

d = a - b
print('a - b =', d)

e = a * b
print('a * b =', e)


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
--------------------------------------------------
    a = [9 5 3 6 9]
    b = [2 5 1 8 9]
a + b = [11 10  4 14 18]
a - b = [ 7  0  2 -2  0]
a * b = [18 25  3 48 81]


In [150]:
import numpy as np
print('6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.')
print('-'*50)

a = np.random.rand(7)
print('a =\n', a)

b = np.random.rand(7)
print('b =\n', b)

c = np.dot(a, b)
print('Скалярний добуток:\n', c)

6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
--------------------------------------------------
a =
 [0.63913611 0.43929053 0.74838698 0.34559676 0.31495019 0.42368347
 0.47710945]
b =
 [0.3477926  0.72577018 0.25972769 0.24794626 0.09652281 0.08727224
 0.50480423]
Скалярний добуток:
 1.129399579875119


In [151]:
import numpy as np
print('7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.')
print('-'*50)

a = np.random.randint(1, 11, size=(2,2))
print('a =\n', a)

b = np.random.randint(1, 11, size=(2,3))
print('b =\n', b)

c = np.dot(a, b)
print('Множення матриць:\n', c)

7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
--------------------------------------------------
a =
 [[4 3]
 [2 5]]
b =
 [[ 7  4 10]
 [ 3  2  7]]
Множення матриць:
 [[37 22 61]
 [29 18 55]]


In [152]:
import numpy as np
print('8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.')
print('-'*50)

a = np.random.randint(1, 11, size=(3,3))
print('a =\n', a)

c = np.linalg.inv(a)
print('Обернена матриця:\n', c)

8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
--------------------------------------------------
a =
 [[ 7  2  9]
 [ 8 10  2]
 [ 5  5  4]]
Обернена матриця:
 [[ 0.39473684  0.48684211 -1.13157895]
 [-0.28947368 -0.22368421  0.76315789]
 [-0.13157895 -0.32894737  0.71052632]]


In [153]:
import numpy as np
print('9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.')
print('-'*50)

a = np.random.rand(4,4)
print('a =\n', a)

c = a.T
print('Транспонована матриця:\n', c)

9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
--------------------------------------------------
a =
 [[0.13963955 0.3199996  0.83117641 0.12276662]
 [0.96720512 0.82266029 0.96526361 0.26849223]
 [0.21995119 0.07608059 0.62541722 0.13213534]
 [0.50082736 0.72503521 0.65191828 0.06682758]]
Транспонована матриця:
 [[0.13963955 0.96720512 0.21995119 0.50082736]
 [0.3199996  0.82266029 0.07608059 0.72503521]
 [0.83117641 0.96526361 0.62541722 0.65191828]
 [0.12276662 0.26849223 0.13213534 0.06682758]]


In [154]:
import numpy as np
print('10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.')
print('-'*50)

a = np.random.randint(1, 11, size=(3,4))
print('a =\n', a)

b = np.random.randint(1, 11, size=(4))
print('b =\n', b)

c = np.dot(a, b)
print('Множення матриці на вектор:\n', c)

10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
--------------------------------------------------
a =
 [[7 1 7 9]
 [1 1 7 9]
 [9 1 6 3]]
b =
 [10 10  4  1]
Множення матриці на вектор:
 [117  57 127]


In [155]:
import numpy as np
print('11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.')
print('-'*50)

a = np.random.rand(2,3)
print('a =\n', a)

b = np.random.rand(3)
print('b =\n', b)

c = np.dot(a, b)
print('Множення матриці на вектор:\n', c)

11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
--------------------------------------------------
a =
 [[0.61855276 0.09567983 0.16648827]
 [0.29802185 0.63128859 0.17875833]]
b =
 [0.53398958 0.5796179  0.74728643]
Множення матриці на вектор:
 [0.51017289 0.65863041]


In [156]:
import numpy as np
print('12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.')
print('-'*50)

a = np.random.randint(1, 11, size=(2,2))
print('a =\n', a)

b = np.random.randint(1, 11, size=(2,2))
print('b =\n', b)

c = a * b
print('Поелементне множення:\n', c)

12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
--------------------------------------------------
a =
 [[7 6]
 [1 5]]
b =
 [[ 7 10]
 [ 7  5]]
Поелементне множення:
 [[49 60]
 [ 7 25]]


In [157]:
import numpy as np
print('13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.')
print('-'*50)

a = np.random.randint(1, 11, size=(2,2))
print('a =\n', a)

b = np.random.randint(1, 11, size=(2,2))
print('b =\n', b)

c = a + b
print('Добуток:\n', c)

13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
--------------------------------------------------
a =
 [[ 3 10]
 [10  5]]
b =
 [[3 1]
 [7 8]]
Добуток:
 [[ 6 11]
 [17 13]]


In [158]:
import numpy as np
print('14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.')
print('-'*50)

a = np.random.randint(1, 101, size=(5,5))
print('a =\n', a)

c = a.sum()
print('Сума всіх елементів:\n', c)

14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
--------------------------------------------------
a =
 [[81 40 91 37 22]
 [81 70 81 58 88]
 [23 47 24 87 66]
 [ 6 92 71 25 59]
 [66 36 10 76 14]]
Сума всіх елементів:
 1351


In [159]:
import numpy as np
print('15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.')
print('-'*50)

a = np.random.randint(1, 11, size=(4,4))
print('a =\n', a)

b = np.random.randint(1, 11, size=(4,4))
print('b =\n', b)

c = a - b
print('a - b =\n', c)

15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
--------------------------------------------------
a =
 [[10  3  5  8]
 [ 9  5  6  5]
 [ 1 10  5  1]
 [ 3  3  5  6]]
b =
 [[ 9 10  4  6]
 [10 10  3 10]
 [ 2  2  5 10]
 [ 7  9 10  2]]
a - b =
 [[ 1 -7  1  2]
 [-1 -5  3 -5]
 [-1  8  0 -9]
 [-4 -6 -5  4]]


In [160]:
import numpy as np
print('16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.')
print('-'*50)

a = np.random.rand(3,3)
print('a =\n', a)

b = np.zeros(3, dtype=float)

for i in range(a.shape[0]):
  b[i] = a[i].sum()

c = b.reshape(-1, 1)
print('Суми елементів кожного рядка матриці:\n',c)


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
--------------------------------------------------
a =
 [[0.70443968 0.22979348 0.62056451]
 [0.26216053 0.34007822 0.42902782]
 [0.6344004  0.48250845 0.90258769]]
Суми елементів кожного рядка матриці:
 [[1.55479767]
 [1.03126657]
 [2.01949653]]


In [161]:
import numpy as np
print('17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.')
print('-'*50)

a = np.random.randint(1, 11, size=(3,4))
print('a =\n', a)

b = np.power(a, 2)
print('a ** 2 =\n', b)

17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
--------------------------------------------------
a =
 [[1 7 9 5]
 [8 6 3 6]
 [7 9 7 2]]
a ** 2 =
 [[ 1 49 81 25]
 [64 36  9 36]
 [49 81 49  4]]


In [162]:
import numpy as np
print('18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.')
print('-'*50)

a = np.random.randint(1, 51, size=(4))
print('a =\n', a)

b = np.sqrt(a)
print('sqrt(a) =\n', b)

18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.
--------------------------------------------------
a =
 [41 40 21 31]
sqrt(a) =
 [6.40312424 6.32455532 4.58257569 5.56776436]
