# Модуль 1. Знайомство з Data Science

#### 1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [2]:
import numpy as np

# a = np.array([1,2,3,4,5,6,7,8,9,10])
a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


#### 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [3]:
import numpy as np

print('варіант 1:')
a = np.array([[0,0,0],[0,0,0],[0,0,0]])
print(a)

print('варіант 2:')
b = np.zeros((3,3), dtype=int)
print(b)

варіант 1:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
варіант 2:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


#### 3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.'

In [4]:
import numpy as np

a = np.random.randint(1, 11, size=(5,5))
print(a)

[[3 8 2 4 1]
 [7 3 7 3 8]
 [2 7 3 9 6]
 [5 6 2 6 7]
 [8 9 8 3 1]]


#### 4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [5]:
import numpy as np

a = np.random.rand(4,4)
print(a)

[[0.0776956  0.02557537 0.6941127  0.03772879]
 [0.02258154 0.89500251 0.70003803 0.77366891]
 [0.56048824 0.92590227 0.37525303 0.36479845]
 [0.63568801 0.13714168 0.69682407 0.63058311]]


#### 5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [6]:
import numpy as np

a = np.random.randint(1, 11, size=(5))
print('    a =', a)

b = np.random.randint(1, 11, size=(5))
print('    b =', b)

c = a + b
print('a + b =', c)

d = a - b
print('a - b =', d)

e = a * b
print('a * b =', e)


    a = [1 9 7 5 3]
    b = [1 2 5 8 6]
a + b = [ 2 11 12 13  9]
a - b = [ 0  7  2 -3 -3]
a * b = [ 1 18 35 40 18]


#### 6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [7]:
import numpy as np

a = np.random.rand(7)
print('a =\n', a)

b = np.random.rand(7)
print('b =\n', b)

c = np.dot(a, b)
print('Скалярний добуток:', c)

a =
 [0.74128023 0.11723595 0.40651047 0.47620569 0.54860254 0.20161275
 0.52362247]
b =
 [0.85095958 0.70253342 0.99746894 0.59755052 0.69212036 0.8650947
 0.60725698]
Скалярний добуток: 2.2752867177374725


#### 7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [8]:
import numpy as np

a = np.random.randint(1, 11, size=(2,2))
print('a =\n', a)

b = np.random.randint(1, 11, size=(2,3))
print('b =\n', b)

c = np.dot(a, b)
print('Множення матриць:\n', c)

a =
 [[6 6]
 [4 2]]
b =
 [[ 4 10  9]
 [10  4  5]]
Множення матриць:
 [[84 84 84]
 [36 48 46]]


#### 8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [9]:
import numpy as np

a = np.random.randint(1, 11, size=(3,3))
print('a =\n', a)

c = np.linalg.inv(a)
print('Обернена матриця:\n', c)

a =
 [[ 2  5  1]
 [ 4  1 10]
 [ 1  3  9]]
Обернена матриця:
 [[ 0.13043478  0.26086957 -0.30434783]
 [ 0.16149068 -0.10559006  0.09937888]
 [-0.06832298  0.00621118  0.11180124]]


#### 9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [10]:
import numpy as np

a = np.random.rand(4,4)
print('a =\n', a)

c = a.T
print('Транспонована матриця:\n', c)

a =
 [[0.03611308 0.04362746 0.06949558 0.24471184]
 [0.6542652  0.3948421  0.02706994 0.1736683 ]
 [0.0363077  0.45158868 0.39151277 0.13141954]
 [0.53153449 0.44121203 0.80769884 0.96415048]]
Транспонована матриця:
 [[0.03611308 0.6542652  0.0363077  0.53153449]
 [0.04362746 0.3948421  0.45158868 0.44121203]
 [0.06949558 0.02706994 0.39151277 0.80769884]
 [0.24471184 0.1736683  0.13141954 0.96415048]]


#### 10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [11]:
import numpy as np

a = np.random.randint(1, 11, size=(3,4))
print('a =\n', a)

b = np.random.randint(1, 11, size=(4))
print('b =\n', b)

c = np.dot(a, b)
print('Множення матриці на вектор:\n', c)

a =
 [[10  9  8  2]
 [ 7 10  7  1]
 [ 1  1  1  4]]
b =
 [10  8 10  6]
Множення матриці на вектор:
 [264 226  52]


#### 11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [12]:
import numpy as np

a = np.random.rand(2,3)
print('a =\n', a)

b = np.random.rand(3)
print('b =\n', b)

c = np.dot(a, b)
print('Множення матриці на вектор:\n', c)

a =
 [[0.87297604 0.09838255 0.42041939]
 [0.84344714 0.38498729 0.23486222]]
b =
 [0.66751365 0.98747276 0.73960988]
Множення матриці на вектор:
 [0.99081984 1.11688337]


#### 12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [13]:
import numpy as np

a = np.random.randint(1, 11, size=(2,2))
print('a =\n', a)

b = np.random.randint(1, 11, size=(2,2))
print('b =\n', b)

c = a * b
print('Поелементне множення:\n', c)

a =
 [[5 1]
 [9 3]]
b =
 [[ 3  2]
 [10  3]]
Поелементне множення:
 [[15  2]
 [90  9]]


#### 13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [14]:
import numpy as np

a = np.random.randint(1, 11, size=(2,2))
print('a =\n', a)

b = np.random.randint(1, 11, size=(2,2))
print('b =\n', b)

c = a + b
print('Добуток:\n', c)

a =
 [[2 8]
 [2 4]]
b =
 [[6 6]
 [1 4]]
Добуток:
 [[ 8 14]
 [ 3  8]]


#### 14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [15]:
import numpy as np

a = np.random.randint(1, 101, size=(5,5))
print('a =\n', a)

c = a.sum()
print('Сума всіх елементів:\n', c)

a =
 [[49  5 81 59 96]
 [79 63 70 52 92]
 [81 12 24 21  7]
 [97 40 82 64  1]
 [19 34 78 86 93]]
Сума всіх елементів:
 1385


#### 15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [16]:
import numpy as np

a = np.random.randint(1, 11, size=(4,4))
print('a =\n', a)

b = np.random.randint(1, 11, size=(4,4))
print('b =\n', b)

c = a - b
print('a - b =\n', c)

a =
 [[ 2  4 10  1]
 [ 1 10  1  6]
 [ 2  2  2  4]
 [ 3  8  2  1]]
b =
 [[7 6 4 8]
 [9 6 3 8]
 [8 7 4 3]
 [3 5 8 1]]
a - b =
 [[-5 -2  6 -7]
 [-8  4 -2 -2]
 [-6 -5 -2  1]
 [ 0  3 -6  0]]


#### 16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [17]:
import numpy as np

a = np.random.rand(3,3)
print('a =\n', a)

# варіант 1:
b = np.zeros(3, dtype=float)

for i in range(a.shape[0]):
  b[i] = a[i].sum()

c = b.reshape(-1, 1)
print('Суми елементів кожного рядка матриці:\n',c)

# варіант 2:
row_sums = np.sum(a, axis=1, keepdims=True)
print('Вектор-стовпчик, що містить суму елементів кожного рядка матриці:\n', row_sums)


a =
 [[0.12928449 0.35643664 0.90283182]
 [0.59952989 0.74397109 0.78436446]
 [0.60960525 0.99022924 0.62016939]]
Суми елементів кожного рядка матриці:
 [[1.38855296]
 [2.12786545]
 [2.22000388]]
Вектор-стовпчик, що містить суму елементів кожного рядка матриці:
 [[1.38855296]
 [2.12786545]
 [2.22000388]]


#### 17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [18]:
import numpy as np

a = np.random.randint(1, 11, size=(3,4))
print('a =\n', a)

b = np.power(a, 2)
print('a ** 2 =\n', b)

a =
 [[ 9  3  5  3]
 [ 1  1  5  6]
 [10  9  2  8]]
a ** 2 =
 [[ 81   9  25   9]
 [  1   1  25  36]
 [100  81   4  64]]


#### 18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [19]:
import numpy as np

a = np.random.randint(1, 51, size=(4))
print('a =\n', a)

b = np.sqrt(a)
print('sqrt(a) =\n', b)

a =
 [42 11  8 34]
sqrt(a) =
 [6.4807407  3.31662479 2.82842712 5.83095189]
