# Модуль 1. Знайомство з Data Science

In [46]:
import numpy as np

#### 1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [47]:
# a = np.array([1,2,3,4,5,6,7,8,9,10])
a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


#### 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [48]:
print('варіант 1:')
a = np.array([[0,0,0],[0,0,0],[0,0,0]])
print(a)

print('варіант 2:')
b = np.zeros((3,3), dtype=int)
print(b)

варіант 1:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
варіант 2:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


#### 3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.'

In [49]:
a = np.random.randint(1, 11, size=(5,5))
print(a)

[[10  8  2  8  9]
 [ 6  4  7  9  9]
 [ 7  4 10  6  3]
 [ 5  1  4  2  4]
 [ 8  8 10  1  5]]


#### 4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [50]:
a = np.random.rand(4,4)
print(a)

[[0.15352473 0.31856849 0.221549   0.82309402]
 [0.60112112 0.72876182 0.98084049 0.07057676]
 [0.35133416 0.16065722 0.91283719 0.76398616]
 [0.47348371 0.0222663  0.11875727 0.73546872]]


#### 5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [51]:
a = np.random.randint(1, 11, size=(5))
print('    a =', a)

b = np.random.randint(1, 11, size=(5))
print('    b =', b)

c = a + b
print('a + b =', c)

d = a - b
print('a - b =', d)

e = a * b
print('a * b =', e)


    a = [ 6  1 10  8  6]
    b = [8 9 3 8 2]
a + b = [14 10 13 16  8]
a - b = [-2 -8  7  0  4]
a * b = [48  9 30 64 12]


#### 6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [52]:
a = np.random.rand(7)
print('a =\n', a)

b = np.random.rand(7)
print('b =\n', b)

c = np.dot(a, b)
print('Скалярний добуток:', c)

a =
 [0.70183978 0.98143445 0.80500514 0.15092456 0.99253863 0.02769579
 0.25869747]
b =
 [0.03073599 0.89609162 0.77883408 0.33731149 0.30695311 0.36539598
 0.6609989 ]
Скалярний добуток: 2.064682434737405


#### 7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [53]:
a = np.random.randint(1, 11, size=(2,2))
print('a =\n', a)

b = np.random.randint(1, 11, size=(2,3))
print('b =\n', b)

c = np.dot(a, b)
print('Множення матриць:\n', c)

a =
 [[10  8]
 [ 9  2]]
b =
 [[9 2 4]
 [5 8 2]]
Множення матриць:
 [[130  84  56]
 [ 91  34  40]]


#### 8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [54]:
a = np.random.randint(1, 11, size=(3,3))
print('a =\n', a)

c = np.linalg.inv(a)
print('Обернена матриця:\n', c)

a =
 [[1 2 9]
 [2 8 2]
 [7 8 6]]
Обернена матриця:
 [[-0.09876543 -0.18518519  0.20987654]
 [-0.00617284  0.17592593 -0.04938272]
 [ 0.12345679 -0.01851852 -0.01234568]]


#### 9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [55]:
a = np.random.rand(4,4)
print('a =\n', a)

c = a.T
print('Транспонована матриця:\n', c)

a =
 [[0.99839273 0.13332902 0.61875657 0.295102  ]
 [0.18451468 0.34512205 0.52640137 0.24018661]
 [0.11121814 0.30550036 0.7721041  0.36658502]
 [0.39583147 0.47216128 0.32445238 0.04108456]]
Транспонована матриця:
 [[0.99839273 0.18451468 0.11121814 0.39583147]
 [0.13332902 0.34512205 0.30550036 0.47216128]
 [0.61875657 0.52640137 0.7721041  0.32445238]
 [0.295102   0.24018661 0.36658502 0.04108456]]


#### 10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [56]:
a = np.random.randint(1, 11, size=(3,4))
print('a =\n', a)

b = np.random.randint(1, 11, size=(4))
print('b =\n', b)

c = np.dot(a, b)
print('Множення матриці на вектор:\n', c)

a =
 [[ 3  9  5  9]
 [10  2  5  1]
 [ 4  6  4  1]]
b =
 [8 2 6 8]
Множення матриці на вектор:
 [144 122  76]


#### 11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [57]:
a = np.random.rand(2,3)
print('a =\n', a)

b = np.random.rand(3)
print('b =\n', b)

c = np.dot(a, b)
print('Множення матриці на вектор:\n', c)

a =
 [[0.01639075 0.93321184 0.89739973]
 [0.93882716 0.42488918 0.27339527]]
b =
 [0.15266289 0.45533901 0.33449415]
Множення матриці на вектор:
 [0.72760497 0.42824181]


#### 12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [58]:
a = np.random.randint(1, 11, size=(2,2))
print('a =\n', a)

b = np.random.randint(1, 11, size=(2,2))
print('b =\n', b)

c = a * b
print('Поелементне множення:\n', c)

a =
 [[ 4  6]
 [ 5 10]]
b =
 [[10  8]
 [ 9  4]]
Поелементне множення:
 [[40 48]
 [45 40]]


#### 13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [59]:
a = np.random.randint(1, 11, size=(2,2))
print('a =\n', a)

b = np.random.randint(1, 11, size=(2,2))
print('b =\n', b)

c = a + b
print('Добуток:\n', c)

a =
 [[5 5]
 [4 6]]
b =
 [[5 2]
 [5 2]]
Добуток:
 [[10  7]
 [ 9  8]]


#### 14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [60]:
a = np.random.randint(1, 101, size=(5,5))
print('a =\n', a)

c = a.sum()
print('Сума всіх елементів:\n', c)

a =
 [[59 63 91 66 28]
 [45 14 11 61 25]
 [17 51  6 43 17]
 [10 11 32 76 26]
 [66  9 55 13 20]]
Сума всіх елементів:
 915


#### 15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [61]:
a = np.random.randint(1, 11, size=(4,4))
print('a =\n', a)

b = np.random.randint(1, 11, size=(4,4))
print('b =\n', b)

c = a - b
print('a - b =\n', c)

a =
 [[ 5 10  7  3]
 [ 2  6 10  7]
 [ 2 10 10 10]
 [ 8 10  8  1]]
b =
 [[3 8 5 5]
 [5 3 7 6]
 [9 9 1 5]
 [5 7 5 1]]
a - b =
 [[ 2  2  2 -2]
 [-3  3  3  1]
 [-7  1  9  5]
 [ 3  3  3  0]]


#### 16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [62]:
a = np.random.rand(3,3)
print('a =\n', a)

# варіант 1:
b = np.zeros(3, dtype=float)

for i in range(a.shape[0]):
  b[i] = a[i].sum()

c = b.reshape(-1, 1)
print('Суми елементів кожного рядка матриці:\n',c)

# варіант 2:
d = np.sum(a, axis=1, keepdims=True)
print('Вектор-стовпчик, що містить суму елементів кожного рядка матриці:\n', d)


a =
 [[0.43101278 0.65786202 0.88631545]
 [0.70414537 0.28998706 0.06473388]
 [0.53098652 0.87566837 0.97081768]]
Суми елементів кожного рядка матриці:
 [[1.97519025]
 [1.05886631]
 [2.37747257]]
Вектор-стовпчик, що містить суму елементів кожного рядка матриці:
 [[1.97519025]
 [1.05886631]
 [2.37747257]]


#### 17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [63]:
a = np.random.randint(1, 11, size=(3,4))
print('a =\n', a)

b = np.power(a, 2)
print('a ** 2 =\n', b)

a =
 [[ 2  5  2 10]
 [ 6  7  5 10]
 [ 1 10  3  1]]
a ** 2 =
 [[  4  25   4 100]
 [ 36  49  25 100]
 [  1 100   9   1]]


#### 18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [64]:
a = np.random.randint(1, 51, size=(4))
print('a =\n', a)

b = np.sqrt(a)
print('sqrt(a) =\n', b)

a =
 [29 49  9 50]
sqrt(a) =
 [5.38516481 7.         3.         7.07106781]
