# Модуль 1. Знайомство з Data Science

#### 1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [19]:
import numpy as np

# a = np.array([1,2,3,4,5,6,7,8,9,10])
a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


#### 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [20]:
import numpy as np

print('варіант 1:')
a = np.array([[0,0,0],[0,0,0],[0,0,0]])
print(a)

print('варіант 2:')
b = np.zeros((3,3), dtype=int)
print(b)

варіант 1:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
варіант 2:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


#### 3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.'

In [21]:
import numpy as np

a = np.random.randint(1, 11, size=(5,5))
print(a)

[[ 8 10  5  7  2]
 [ 5  6  9  7  5]
 [ 4  2  1  5  2]
 [10  8  3  5 10]
 [ 2  7  7  9  9]]


#### 4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [22]:
import numpy as np

a = np.random.rand(4,4)
print(a)

[[0.53494557 0.59592452 0.20804523 0.99606285]
 [0.91534898 0.70685011 0.75208055 0.87747652]
 [0.1369444  0.70255957 0.74581669 0.64090694]
 [0.90805809 0.270617   0.11681839 0.46379567]]


#### 5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [23]:
import numpy as np

a = np.random.randint(1, 11, size=(5))
print('    a =', a)

b = np.random.randint(1, 11, size=(5))
print('    b =', b)

c = a + b
print('a + b =', c)

d = a - b
print('a - b =', d)

e = a * b
print('a * b =', e)


    a = [5 2 6 5 3]
    b = [1 7 4 4 1]
a + b = [ 6  9 10  9  4]
a - b = [ 4 -5  2  1  2]
a * b = [ 5 14 24 20  3]


#### 6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [24]:
import numpy as np

a = np.random.rand(7)
print('a =\n', a)

b = np.random.rand(7)
print('b =\n', b)

c = np.dot(a, b)
print('Скалярний добуток:', c)

a =
 [0.89487487 0.01242619 0.74448348 0.19294176 0.66587475 0.94162818
 0.50996722]
b =
 [0.71519852 0.39145306 0.96110389 0.20849145 0.19579151 0.41747849
 0.69703841]
Скалярний добуток: 2.2795790147757558


#### 7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [25]:
import numpy as np

a = np.random.randint(1, 11, size=(2,2))
print('a =\n', a)

b = np.random.randint(1, 11, size=(2,3))
print('b =\n', b)

c = np.dot(a, b)
print('Множення матриць:\n', c)

a =
 [[ 3  8]
 [10  4]]
b =
 [[6 2 4]
 [4 6 3]]
Множення матриць:
 [[50 54 36]
 [76 44 52]]


#### 8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [26]:
import numpy as np

a = np.random.randint(1, 11, size=(3,3))
print('a =\n', a)

c = np.linalg.inv(a)
print('Обернена матриця:\n', c)

a =
 [[ 5  6  5]
 [ 5  8  1]
 [ 5  6 10]]
Обернена матриця:
 [[ 1.48 -0.6  -0.68]
 [-0.9   0.5   0.4 ]
 [-0.2   0.    0.2 ]]


#### 9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [27]:
import numpy as np

a = np.random.rand(4,4)
print('a =\n', a)

c = a.T
print('Транспонована матриця:\n', c)

a =
 [[0.21623315 0.02983664 0.82921435 0.01316195]
 [0.10313903 0.4023312  0.0838395  0.09412469]
 [0.06354372 0.65954074 0.72480516 0.59603041]
 [0.34702925 0.41680523 0.04527043 0.16965644]]
Транспонована матриця:
 [[0.21623315 0.10313903 0.06354372 0.34702925]
 [0.02983664 0.4023312  0.65954074 0.41680523]
 [0.82921435 0.0838395  0.72480516 0.04527043]
 [0.01316195 0.09412469 0.59603041 0.16965644]]


#### 10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [28]:
import numpy as np

a = np.random.randint(1, 11, size=(3,4))
print('a =\n', a)

b = np.random.randint(1, 11, size=(4))
print('b =\n', b)

c = np.dot(a, b)
print('Множення матриці на вектор:\n', c)

a =
 [[ 3 10  4  1]
 [ 3  5  7  8]
 [ 8  8  3 10]]
b =
 [3 3 4 7]
Множення матриці на вектор:
 [ 62 108 130]


#### 11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [29]:
import numpy as np

a = np.random.rand(2,3)
print('a =\n', a)

b = np.random.rand(3)
print('b =\n', b)

c = np.dot(a, b)
print('Множення матриці на вектор:\n', c)

a =
 [[0.17784559 0.03968314 0.05188573]
 [0.3637767  0.6562323  0.10800951]]
b =
 [0.8654883  0.73253265 0.24296902]
Множення матриці на вектор:
 [0.1955991  0.82179903]


#### 12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [30]:
import numpy as np

a = np.random.randint(1, 11, size=(2,2))
print('a =\n', a)

b = np.random.randint(1, 11, size=(2,2))
print('b =\n', b)

c = a * b
print('Поелементне множення:\n', c)

a =
 [[5 9]
 [3 2]]
b =
 [[4 9]
 [9 7]]
Поелементне множення:
 [[20 81]
 [27 14]]


#### 13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [31]:
import numpy as np

a = np.random.randint(1, 11, size=(2,2))
print('a =\n', a)

b = np.random.randint(1, 11, size=(2,2))
print('b =\n', b)

c = a + b
print('Добуток:\n', c)

a =
 [[8 4]
 [7 7]]
b =
 [[ 2  6]
 [ 1 10]]
Добуток:
 [[10 10]
 [ 8 17]]


#### 14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [32]:
import numpy as np

a = np.random.randint(1, 101, size=(5,5))
print('a =\n', a)

c = a.sum()
print('Сума всіх елементів:\n', c)

a =
 [[24 11 79 55 25]
 [76  5 22  5 67]
 [80 28 14 75 67]
 [90 59 91 49 40]
 [54 72 33 23 27]]
Сума всіх елементів:
 1171


#### 15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [33]:
import numpy as np

a = np.random.randint(1, 11, size=(4,4))
print('a =\n', a)

b = np.random.randint(1, 11, size=(4,4))
print('b =\n', b)

c = a - b
print('a - b =\n', c)

a =
 [[ 5  4  9  3]
 [10  2  7  2]
 [ 7  8  4  2]
 [ 7  9  5  3]]
b =
 [[10  1  6  3]
 [ 6  2  8  1]
 [ 6  6  2  7]
 [ 3  7  7  9]]
a - b =
 [[-5  3  3  0]
 [ 4  0 -1  1]
 [ 1  2  2 -5]
 [ 4  2 -2 -6]]


#### 16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [34]:
import numpy as np

a = np.random.rand(3,3)
print('a =\n', a)

# варіант 1:
b = np.zeros(3, dtype=float)

for i in range(a.shape[0]):
  b[i] = a[i].sum()

c = b.reshape(-1, 1)
print('Суми елементів кожного рядка матриці:\n',c)

# варіант 2:
row_sums = np.sum(a, axis=1, keepdims=True)
print('Вектор-стовпчик, що містить суму елементів кожного рядка матриці:\n', row_sums)


a =
 [[0.38693087 0.27481979 0.78326015]
 [0.19239966 0.3041641  0.01010333]
 [0.43966383 0.67127383 0.83543315]]
Суми елементів кожного рядка матриці:
 [[1.4450108 ]
 [0.50666708]
 [1.94637081]]
Вектор-стовпчик, що містить суму елементів кожного рядка матриці:
 [[1.4450108 ]
 [0.50666708]
 [1.94637081]]


#### 17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [35]:
import numpy as np

a = np.random.randint(1, 11, size=(3,4))
print('a =\n', a)

b = np.power(a, 2)
print('a ** 2 =\n', b)

a =
 [[ 7 10  8  2]
 [ 5 10 10  2]
 [ 7  3  6  6]]
a ** 2 =
 [[ 49 100  64   4]
 [ 25 100 100   4]
 [ 49   9  36  36]]


#### 18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [36]:
import numpy as np

a = np.random.randint(1, 51, size=(4))
print('a =\n', a)

b = np.sqrt(a)
print('sqrt(a) =\n', b)

a =
 [28 30 15 37]
sqrt(a) =
 [5.29150262 5.47722558 3.87298335 6.08276253]
