<a href="https://colab.research.google.com/github/KyryloChalov/DS/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import numpy as np
print('1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.')
print('-'*50)

a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a)

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
--------------------------------------------------
[ 1  2  3  4  5  6  7  8  9 10]


In [38]:
import numpy as np
print('2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.')
print('-'*50)

print('варіант 1:')
a = np.array([[0,0,0],[0,0,0],[0,0,0]])
print(a)

print('варіант 2:')
b = np.zeros((3,3), dtype=int)
print(b)

2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
--------------------------------------------------
варіант 1:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
варіант 2:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [39]:
import numpy as np
print('3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.')
print('-'*50)

a = np.random.randint(1, 11, size=(5,5))
print(a)

3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
--------------------------------------------------
[[ 7  3  4  8  8]
 [ 1  8  1  9  9]
 [ 7  6  3  5  6]
 [ 5  9  7 10  9]
 [ 6  7  9  6  4]]


In [40]:
import numpy as np
print('4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.')
print('-'*50)

a = np.random.rand(4,4)
print(a)

4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
--------------------------------------------------
[[0.96753592 0.85182384 0.21253927 0.44559913]
 [0.38778105 0.62752782 0.64523487 0.45250581]
 [0.57806532 0.98726726 0.99839547 0.71558441]
 [0.2838964  0.36336106 0.15952105 0.94254138]]


In [41]:
import numpy as np
print('5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.')
print('-'*50)

a = np.random.randint(1, 11, size=(5))
print('    a =', a)

b = np.random.randint(1, 11, size=(5))
print('    b =', b)

c = a + b
print('a + b =', c)

d = a - b
print('a - b =', d)

e = a * b
print('a * b =', e)


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
--------------------------------------------------
    a = [3 9 5 8 7]
    b = [2 5 2 2 5]
a + b = [ 5 14  7 10 12]
a - b = [1 4 3 6 2]
a * b = [ 6 45 10 16 35]


In [42]:
import numpy as np
print('6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.')
print('-'*50)

a = np.random.rand(7)
print('a =\n', a)

b = np.random.rand(7)
print('b =\n', b)

c = np.dot(a, b)
print('Скалярний добуток:\n', c)

6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
--------------------------------------------------
a =
 [0.93026433 0.83353137 0.6822146  0.15013301 0.56701705 0.27935803
 0.00873853]
b =
 [0.17453643 0.87672118 0.16615068 0.26267318 0.03517928 0.088092
 0.27379594]
Скалярний добуток:
 1.092874982477654


In [43]:
import numpy as np
print('7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.')
print('-'*50)

a = np.random.randint(1, 11, size=(2,2))
print('a =\n', a)

b = np.random.randint(1, 11, size=(2,3))
print('b =\n', b)

c = np.dot(a, b)
print('Множення матриць:\n', c)

7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
--------------------------------------------------
a =
 [[4 5]
 [2 2]]
b =
 [[10  8  1]
 [ 6  3  7]]
Множення матриць:
 [[70 47 39]
 [32 22 16]]


In [44]:
import numpy as np
print('8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.')
print('-'*50)

a = np.random.randint(1, 11, size=(3,3))
print('a =\n', a)

c = np.linalg.inv(a)
print('Обернена матриця:\n', c)

8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
--------------------------------------------------
a =
 [[6 8 3]
 [2 4 2]
 [1 4 1]]
Обернена матриця:
 [[ 0.33333333 -0.33333333 -0.33333333]
 [ 0.         -0.25        0.5       ]
 [-0.33333333  1.33333333 -0.66666667]]


In [45]:
import numpy as np
print('9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.')
print('-'*50)

a = np.random.rand(4,4)
print('a =\n', a)

c = a.T
print('Транспонована матриця:\n', c)

9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
--------------------------------------------------
a =
 [[0.58481365 0.2447076  0.13179375 0.20578669]
 [0.29345884 0.54954173 0.16318293 0.95471073]
 [0.28919682 0.87137187 0.03706757 0.4365368 ]
 [0.9833603  0.05068796 0.35151897 0.07972216]]
Транспонована матриця:
 [[0.58481365 0.29345884 0.28919682 0.9833603 ]
 [0.2447076  0.54954173 0.87137187 0.05068796]
 [0.13179375 0.16318293 0.03706757 0.35151897]
 [0.20578669 0.95471073 0.4365368  0.07972216]]


In [46]:
import numpy as np
print('10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.')
print('-'*50)

a = np.random.randint(1, 11, size=(3,4))
print('a =\n', a)

b = np.random.randint(1, 11, size=(4))
print('b =\n', b)

c = np.dot(a, b)
print('Множення матриці на вектор:\n', c)

10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
--------------------------------------------------
a =
 [[3 2 6 6]
 [8 4 3 9]
 [7 4 1 5]]
b =
 [ 1  4 10  4]
Множення матриці на вектор:
 [95 90 53]


In [47]:
import numpy as np
print('11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.')
print('-'*50)

a = np.random.rand(2,3)
print('a =\n', a)

b = np.random.rand(3)
print('b =\n', b)

c = np.dot(a, b)
print('Множення матриці на вектор:\n', c)

11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
--------------------------------------------------
a =
 [[0.68367745 0.04997623 0.32120537]
 [0.41740754 0.72007894 0.24641286]]
b =
 [0.47593015 0.93049901 0.0078856 ]
Множення матриці на вектор:
 [0.37441844 0.87063269]


In [48]:
import numpy as np
print('12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.')
print('-'*50)

a = np.random.randint(1, 11, size=(2,2))
print('a =\n', a)

b = np.random.randint(1, 11, size=(2,2))
print('b =\n', b)

c = a * b
print('Поелементне множення:\n', c)

12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
--------------------------------------------------
a =
 [[1 4]
 [2 2]]
b =
 [[5 1]
 [8 6]]
Поелементне множення:
 [[ 5  4]
 [16 12]]


In [49]:
import numpy as np
print('13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.')
print('-'*50)

a = np.random.randint(1, 11, size=(2,2))
print('a =\n', a)

b = np.random.randint(1, 11, size=(2,2))
print('b =\n', b)

c = a + b
print('Добуток:\n', c)

13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
--------------------------------------------------
a =
 [[ 7  3]
 [10  6]]
b =
 [[4 9]
 [8 8]]
Добуток:
 [[11 12]
 [18 14]]


In [50]:
import numpy as np
print('14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.')
print('-'*50)

a = np.random.randint(1, 101, size=(5,5))
print('a =\n', a)

c = a.sum()
print('Сума всіх елементів:\n', c)

14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
--------------------------------------------------
a =
 [[85 53 55 34 82]
 [90 21 18 97 46]
 [78 17 85 70 63]
 [39 34 29  1 40]
 [13 10  6 74 22]]
Сума всіх елементів:
 1162


In [51]:
import numpy as np
print('15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.')
print('-'*50)

a = np.random.randint(1, 11, size=(4,4))
print('a =\n', a)

b = np.random.randint(1, 11, size=(4,4))
print('b =\n', b)

c = a - b
print('a - b =\n', c)

15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
--------------------------------------------------
a =
 [[ 8  7  9 10]
 [ 7  1  1  6]
 [ 4  3 10  1]
 [ 1  7  8  5]]
b =
 [[ 4  8  4  6]
 [ 9  7 10  3]
 [ 9  3  4  5]
 [ 2  5  5  9]]
a - b =
 [[ 4 -1  5  4]
 [-2 -6 -9  3]
 [-5  0  6 -4]
 [-1  2  3 -4]]


In [52]:
import numpy as np
print('16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.')
print('-'*50)

a = np.random.rand(3,3)
print('a =\n', a)

b = np.zeros(3, dtype=float)

for i in range(a.shape[0]):
  b[i] = a[i].sum()

c = b.reshape(-1, 1)
print('Суми елементів кожного рядка матриці:\n',c)


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
--------------------------------------------------
a =
 [[0.71172694 0.21608206 0.13362645]
 [0.33633235 0.03041922 0.50820972]
 [0.99584785 0.15896642 0.38253078]]
Суми елементів кожного рядка матриці:
 [[1.06143545]
 [0.87496129]
 [1.53734505]]


In [53]:
import numpy as np
print('17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.')
print('-'*50)

a = np.random.randint(1, 11, size=(3,4))
print('a =\n', a)

b = np.power(a, 2)
print('a ** 2 =\n', b)

17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
--------------------------------------------------
a =
 [[10  7  8  5]
 [ 1  3  3  2]
 [ 7  6  8  8]]
a ** 2 =
 [[100  49  64  25]
 [  1   9   9   4]
 [ 49  36  64  64]]


In [54]:
import numpy as np
print('18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.')
print('-'*50)

a = np.random.randint(1, 51, size=(4))
print('a =\n', a)

b = np.sqrt(a)
print('sqrt(a) =\n', b)

18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.
--------------------------------------------------
a =
 [40 22 31 15]
sqrt(a) =
 [6.32455532 4.69041576 5.56776436 3.87298335]
