# Модуль 1. Знайомство з Data Science

In [20]:
import numpy as np

#### 1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [21]:
# a = np.array([1,2,3,4,5,6,7,8,9,10])
a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


#### 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [22]:
print('варіант 1:')
a = np.array([[0,0,0],[0,0,0],[0,0,0]])
print(a)

print('варіант 2:')
b = np.zeros((3,3), dtype=int)
print(b)

варіант 1:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
варіант 2:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


#### 3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.'

In [23]:
a = np.random.randint(1, 11, size=(5,5))
print(a)

[[ 9 10  3  7  7]
 [ 7  4  1  1  7]
 [ 5  3  9  1  4]
 [ 9  2  4  4 10]
 [ 6  6  9  6  1]]


#### 4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [24]:
a = np.random.rand(4,4)
print(a)

[[0.81690469 0.87529236 0.81070584 0.7077694 ]
 [0.39955578 0.72389484 0.42129552 0.5996795 ]
 [0.45455976 0.98927817 0.82078029 0.67816927]
 [0.64158252 0.38760503 0.41204584 0.33792529]]


#### 5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [25]:
a = np.random.randint(1, 11, size=(5))
print('    a =', a)

b = np.random.randint(1, 11, size=(5))
print('    b =', b)

c = a + b
print('a + b =', c)

d = a - b
print('a - b =', d)

e = a * b
print('a * b =', e)


    a = [2 8 6 2 6]
    b = [ 6  7  3 10  3]
a + b = [ 8 15  9 12  9]
a - b = [-4  1  3 -8  3]
a * b = [12 56 18 20 18]


#### 6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [26]:
a = np.random.rand(7)
print('a =\n', a)

b = np.random.rand(7)
print('b =\n', b)

c = np.dot(a, b)
print('Скалярний добуток:', c)

a =
 [0.71509749 0.4582476  0.35271899 0.81521073 0.32223779 0.50645169
 0.69360338]
b =
 [0.12701653 0.52051098 0.82125207 0.1093624  0.25948978 0.52664159
 0.52358546]
Скалярний добуток: 1.4216732999070159


#### 7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [27]:
a = np.random.randint(1, 11, size=(2,2))
print('a =\n', a)

b = np.random.randint(1, 11, size=(2,3))
print('b =\n', b)

c = np.dot(a, b)
print('Множення матриць:\n', c)

a =
 [[ 9  9]
 [10  3]]
b =
 [[4 2 4]
 [6 7 3]]
Множення матриць:
 [[90 81 63]
 [58 41 49]]


#### 8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [28]:
a = np.random.randint(1, 11, size=(3,3))
print('a =\n', a)

c = np.linalg.inv(a)
print('Обернена матриця:\n', c)

a =
 [[ 1  2  4]
 [ 4  5 10]
 [ 8  9  7]]
Обернена матриця:
 [[-1.66666667e+00  6.66666667e-01 -2.77555756e-17]
 [ 1.57575758e+00 -7.57575758e-01  1.81818182e-01]
 [-1.21212121e-01  2.12121212e-01 -9.09090909e-02]]


#### 9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [29]:
a = np.random.rand(4,4)
print('a =\n', a)

c = a.T
print('Транспонована матриця:\n', c)

a =
 [[0.97012702 0.75816409 0.84211739 0.91809463]
 [0.15096685 0.64614612 0.20755767 0.78519293]
 [0.36776631 0.83902384 0.38951933 0.18530285]
 [0.7843943  0.70791538 0.97219117 0.99010489]]
Транспонована матриця:
 [[0.97012702 0.15096685 0.36776631 0.7843943 ]
 [0.75816409 0.64614612 0.83902384 0.70791538]
 [0.84211739 0.20755767 0.38951933 0.97219117]
 [0.91809463 0.78519293 0.18530285 0.99010489]]


#### 10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [30]:
a = np.random.randint(1, 11, size=(3,4))
print('a =\n', a)

b = np.random.randint(1, 11, size=(4))
print('b =\n', b)

c = np.dot(a, b)
print('Множення матриці на вектор:\n', c)

a =
 [[4 1 4 9]
 [5 8 8 2]
 [8 6 5 3]]
b =
 [5 6 2 4]
Множення матриці на вектор:
 [70 97 98]


#### 11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [31]:
a = np.random.rand(2,3)
print('a =\n', a)

b = np.random.rand(3)
print('b =\n', b)

c = np.dot(a, b)
print('Множення матриці на вектор:\n', c)

a =
 [[0.34653404 0.56723045 0.8447166 ]
 [0.08702156 0.50101878 0.77699702]]
b =
 [0.4429844  0.89736266 0.58196074]
Множення матриці на вектор:
 [1.1541125 0.9403265]


#### 12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [32]:
a = np.random.randint(1, 11, size=(2,2))
print('a =\n', a)

b = np.random.randint(1, 11, size=(2,2))
print('b =\n', b)

c = a * b
print('Поелементне множення:\n', c)

a =
 [[3 2]
 [3 5]]
b =
 [[1 6]
 [1 3]]
Поелементне множення:
 [[ 3 12]
 [ 3 15]]


#### 13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [33]:
a = np.random.randint(1, 11, size=(2,2))
print('a =\n', a)

b = np.random.randint(1, 11, size=(2,2))
print('b =\n', b)

c = a + b
print('Добуток:\n', c)

a =
 [[4 3]
 [7 2]]
b =
 [[1 3]
 [9 1]]
Добуток:
 [[ 5  6]
 [16  3]]


#### 14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [34]:
a = np.random.randint(1, 101, size=(5,5))
print('a =\n', a)

c = a.sum()
print('Сума всіх елементів:\n', c)

a =
 [[ 8  6  8 30 90]
 [31 51 50 35 80]
 [50 90 16 88 30]
 [45 33 72 27 97]
 [23 87 33 14 32]]
Сума всіх елементів:
 1126


#### 15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [35]:
a = np.random.randint(1, 11, size=(4,4))
print('a =\n', a)

b = np.random.randint(1, 11, size=(4,4))
print('b =\n', b)

c = a - b
print('a - b =\n', c)

a =
 [[ 8  6  7  2]
 [ 3  8 10  4]
 [ 3  6  9  6]
 [ 6  3  9  7]]
b =
 [[ 9  6  3  3]
 [10  3  5  7]
 [ 1  2 10  1]
 [ 7  7  3  5]]
a - b =
 [[-1  0  4 -1]
 [-7  5  5 -3]
 [ 2  4 -1  5]
 [-1 -4  6  2]]


#### 16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [36]:
a = np.random.rand(3,3)
print('a =\n', a)

# варіант 1:
b = np.zeros(3, dtype=float)

for i in range(a.shape[0]):
  b[i] = a[i].sum()

c = b.reshape(-1, 1)
print('Суми елементів кожного рядка матриці:\n',c)

# варіант 2:
d = np.sum(a, axis=1, keepdims=True)
print('Вектор-стовпчик, що містить суму елементів кожного рядка матриці:\n', d)


a =
 [[0.70640454 0.21115247 0.73834969]
 [0.80309274 0.02313181 0.85752989]
 [0.60566446 0.63314295 0.46268729]]
Суми елементів кожного рядка матриці:
 [[1.6559067 ]
 [1.68375444]
 [1.7014947 ]]
Вектор-стовпчик, що містить суму елементів кожного рядка матриці:
 [[1.6559067 ]
 [1.68375444]
 [1.7014947 ]]


#### 17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [37]:
a = np.random.randint(1, 11, size=(3,4))
print('a =\n', a)

b = np.power(a, 2)
print('a ** 2 =\n', b)

a =
 [[ 2  7  2  1]
 [10  6  3  6]
 [ 5  6  7  9]]
a ** 2 =
 [[  4  49   4   1]
 [100  36   9  36]
 [ 25  36  49  81]]


#### 18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [38]:
a = np.random.randint(1, 51, size=(4))
print('a =\n', a)

b = np.sqrt(a)
print('sqrt(a) =\n', b)

a =
 [ 7 10 26  8]
sqrt(a) =
 [2.64575131 3.16227766 5.09901951 2.82842712]
