# Модуль 1. Знайомство з Data Science

In [1]:
import numpy as np

#### 1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [2]:
# a = np.array([1,2,3,4,5,6,7,8,9,10])
a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


#### 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [3]:
print('варіант 1:')
a = np.array([[0,0,0],[0,0,0],[0,0,0]])
print(a)

print('варіант 2:')
b = np.zeros((3,3), dtype=int)
print(b)

варіант 1:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
варіант 2:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


#### 3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.'

In [4]:
a = np.random.randint(1, 11, size=(5,5))
print(a)

[[ 1  3  7  3  2]
 [ 1  5  9  1 10]
 [ 5  2  1  4  2]
 [ 1  1  3  2  7]
 [ 9  8  8  5  1]]


#### 4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [5]:
a = np.random.rand(4,4)
print(a)

[[0.71576467 0.5899471  0.78159561 0.33316701]
 [0.84150666 0.25452375 0.98516622 0.05663379]
 [0.43978787 0.79984896 0.68191799 0.61627251]
 [0.31775097 0.86839363 0.83799254 0.99541916]]


#### 5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [6]:
a = np.random.randint(1, 11, size=(5))
print('    a =', a)

b = np.random.randint(1, 11, size=(5))
print('    b =', b)

c = a + b
print('a + b =', c)

d = a - b
print('a - b =', d)

e = a * b
print('a * b =', e)


    a = [5 9 9 8 7]
    b = [10  4 10  7  5]
a + b = [15 13 19 15 12]
a - b = [-5  5 -1  1  2]
a * b = [50 36 90 56 35]


#### 6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [7]:
a = np.random.rand(7)
print('a =\n', a)

b = np.random.rand(7)
print('b =\n', b)

c = np.dot(a, b)
print('Скалярний добуток:', c)

a =
 [0.29304288 0.86057571 0.03254271 0.8515119  0.02199423 0.93706069
 0.99909051]
b =
 [0.05008294 0.58143866 0.69303567 0.17156106 0.86844851 0.27406627
 0.86352102]
Скалярний добуток: 1.8223412268029753


#### 7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [8]:
a = np.random.randint(1, 11, size=(2,2))
print('a =\n', a)

b = np.random.randint(1, 11, size=(2,3))
print('b =\n', b)

c = np.dot(a, b)
print('Множення матриць:\n', c)

a =
 [[ 2 10]
 [ 4  9]]
b =
 [[1 8 6]
 [4 4 1]]
Множення матриць:
 [[42 56 22]
 [40 68 33]]


#### 8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [9]:
a = np.random.randint(1, 11, size=(3,3))
print('a =\n', a)

c = np.linalg.inv(a)
print('Обернена матриця:\n', c)

a =
 [[2 7 3]
 [6 6 4]
 [3 3 1]]
Обернена матриця:
 [[-0.2         0.06666667  0.33333333]
 [ 0.2        -0.23333333  0.33333333]
 [-0.          0.5        -1.        ]]


#### 9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [10]:
a = np.random.rand(4,4)
print('a =\n', a)

c = a.T
print('Транспонована матриця:\n', c)

a =
 [[0.14715708 0.80899551 0.83620175 0.54049125]
 [0.69343499 0.19489617 0.80938273 0.22232205]
 [0.24161673 0.69638448 0.32561053 0.77452136]
 [0.26622109 0.79607688 0.62768421 0.15026153]]
Транспонована матриця:
 [[0.14715708 0.69343499 0.24161673 0.26622109]
 [0.80899551 0.19489617 0.69638448 0.79607688]
 [0.83620175 0.80938273 0.32561053 0.62768421]
 [0.54049125 0.22232205 0.77452136 0.15026153]]


#### 10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [11]:
a = np.random.randint(1, 11, size=(3,4))
print('a =\n', a)

b = np.random.randint(1, 11, size=(4))
print('b =\n', b)

c = np.dot(a, b)
print('Множення матриці на вектор:\n', c)

a =
 [[ 7  8  4  4]
 [ 7  4 10  4]
 [ 2  9 10  9]]
b =
 [ 4  1  5 10]
Множення матриці на вектор:
 [ 96 122 157]


#### 11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [12]:
a = np.random.rand(2,3)
print('a =\n', a)

b = np.random.rand(3)
print('b =\n', b)

c = np.dot(a, b)
print('Множення матриці на вектор:\n', c)

a =
 [[0.66851762 0.95932631 0.48773384]
 [0.41679264 0.82262828 0.63875215]]
b =
 [0.61525111 0.38612839 0.58086921]
Множення матриці на вектор:
 [1.0650389  0.94510373]


#### 12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [13]:
a = np.random.randint(1, 11, size=(2,2))
print('a =\n', a)

b = np.random.randint(1, 11, size=(2,2))
print('b =\n', b)

c = a * b
print('Поелементне множення:\n', c)

a =
 [[2 8]
 [8 2]]
b =
 [[ 7 10]
 [ 9  5]]
Поелементне множення:
 [[14 80]
 [72 10]]


#### 13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [14]:
a = np.random.randint(1, 11, size=(2,2))
print('a =\n', a)

b = np.random.randint(1, 11, size=(2,2))
print('b =\n', b)

c = a + b
print('Добуток:\n', c)

a =
 [[9 6]
 [2 3]]
b =
 [[10 10]
 [ 7  5]]
Добуток:
 [[19 16]
 [ 9  8]]


#### 14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [15]:
a = np.random.randint(1, 101, size=(5,5))
print('a =\n', a)

c = a.sum()
print('Сума всіх елементів:\n', c)

a =
 [[23 44 20 48 92]
 [ 4 71 29 59 44]
 [46 63 24 34 55]
 [38 20 97 35 21]
 [21 18 88 86 91]]
Сума всіх елементів:
 1171


#### 15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [16]:
a = np.random.randint(1, 11, size=(4,4))
print('a =\n', a)

b = np.random.randint(1, 11, size=(4,4))
print('b =\n', b)

c = a - b
print('a - b =\n', c)

a =
 [[ 6  6  2  6]
 [ 2  9  7 10]
 [ 8  2  9  9]
 [ 4  5  8  3]]
b =
 [[ 7  4  1  5]
 [ 3  6 10  1]
 [ 1  8  2  2]
 [ 8  8  8  6]]
a - b =
 [[-1  2  1  1]
 [-1  3 -3  9]
 [ 7 -6  7  7]
 [-4 -3  0 -3]]


#### 16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [17]:
a = np.random.rand(3,3)
print('a =\n', a)

# варіант 1:
b = np.zeros(3, dtype=float)

for i in range(a.shape[0]):
  b[i] = a[i].sum()

c = b.reshape(-1, 1)
print('Суми елементів кожного рядка матриці:\n',c)

# варіант 2:
d = np.sum(a, axis=1, keepdims=True)
print('Вектор-стовпчик, що містить суму елементів кожного рядка матриці:\n', d)


a =
 [[3.57525070e-01 6.24062350e-04 3.20127645e-01]
 [9.74816526e-01 3.86123387e-02 7.43079718e-01]
 [3.01899550e-01 1.18982017e-01 9.12069562e-01]]
Суми елементів кожного рядка матриці:
 [[0.67827678]
 [1.75650858]
 [1.33295113]]
Вектор-стовпчик, що містить суму елементів кожного рядка матриці:
 [[0.67827678]
 [1.75650858]
 [1.33295113]]


#### 17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [18]:
a = np.random.randint(1, 11, size=(3,4))
print('a =\n', a)

b = np.power(a, 2)
print('a ** 2 =\n', b)

a =
 [[ 2  6  4  8]
 [ 8 10  2 10]
 [ 9  3  6  7]]
a ** 2 =
 [[  4  36  16  64]
 [ 64 100   4 100]
 [ 81   9  36  49]]


#### 18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [19]:
a = np.random.randint(1, 51, size=(4))
print('a =\n', a)

b = np.sqrt(a)
print('sqrt(a) =\n', b)

a =
 [47 39 34  9]
sqrt(a) =
 [6.8556546  6.244998   5.83095189 3.        ]
